name: Deploy to GitHub pages branch
on:
  workflow_dispatch:
  push:
    branches: main
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install deps
        run: npm install
      - name: Build
        run: | 
          npm run-script build:esbuild
          npm run-script build:sass
      - name: Prepare for deploy
        run: |
          rm -rf build
          mkdir -p build
          mv public index.html build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
